baseURL: "https://www.tamnj.org/"
theme: "up-business-theme"
languageCode: "en-us"

title: "தமிழர்கள் மன்றம் குழுவினர்"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "தமிழர்கள் மன்றம் குழுவினர்"
  description: "Thamizhargal Mandram NJ - A Non-Profit 501(C)(3) Tax Exempt Organization"
  images: 
    - "images/logo.png"

  logo: "logo.png"
  bylaws: "pdf/tamilbylaws.pdf"
  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "https://instagram.com/tamnjorg?utm_source=qr&igshid=OGU0MmVlOWVjOQ=="
    facebook: "https://www.facebook.com/profile.php?id=61550886939203&mibextid=ZbWKwL"
    twitter: "https://twitter.com/TAMNJorg"

  location:
    - "155 Polifly Road, Suite 205, Hackensack NJ 07601"

  contact:
    - "tamnjorg@gmail.com"
    - "+1 (973)-963-7488"

  verify:
    - "EIN: 93-2821757"

  copyright: "© 2023 tamnj.org All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Membership"
      url: "/Membership"
      weight: 2

    - name: "About"
      url: "/About"
      weight: 3

    - name: "Events"
      url: "/Events"
      weight: 4
    
    - name: "Sponsors"
      url: "/Sponsored"
      weight: 4

    - name: "Executive Members"
      url: "/executivemembers"
      weight: 4
    

  buttons:
    - name: "Donations"
      url: "/post/donations/"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Membership"
      url: "/Membership"
      weight: 2

    - name: "About"
      url: "/About"
      weight: 3

    - name: "Events"
      url: "/Events"
      weight: 4
    
    - name: "Sponsors"
      url: "/Sponsored"
      weight: 4
    
    - name: "Executive Members"
      url: "/executivemembers"
      weight: 5

    - name: "Bylaws"
      url: "/post/bylaws/"
      weight: 6

taxonomies:
  series: "series"
  tags: "tags"
