baseURL: "https://webstoriez.github.io/tamnj/"
theme: "up-business-theme"
languageCode: "en-us"

title: "தமிழர்கள் மன்றம் குழுவினர்"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "தமிழர்கள் மன்றம் குழுவினர்"
  description: "Thamizhargal Mandram NJ - A Non-Profit 501(C)(3) Tax Exempt Organization"
  images: 
    - "images/logo.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "155 Polifly Road, Suite 205, Hackensack NJ 07601"

  contact:
    - "tamnjorg@gmail.com"
    - "+1 (973)-963-7488"

  copyright: "© 2023 tamnj.org All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Membership"
      url: "/Membership"
      weight: 2

    - name: "About"
      url: "/About"
      weight: 3

    - name: "Events"
      url: "/Events"
      weight: 4
    
    - name: "Sponsor"
      url: "/Sponsor"
      weight: 4
    
    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Become a Member"
      url: "/Join"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Membership"
      url: "/Membership"
      weight: 2

    - name: "About"
      url: "/About"
      weight: 3

    - name: "Events"
      url: "/Events"
      weight: 4
    
    - name: "Sponsor"
      url: "/Sponsor"
      weight: 4
    
    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
